import Head from "next/head";

//mapbox config//



import MainMap from "../components/mainmap";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Geoportal Test</title>
        <meta name='Geoportal Test' content='Generated by create next app' />
        {/* !!!Change Icon!!! */}
        <link rel='icon' href='/favicon.ico' />
        
      </Head>
      {/* <MainMap /> */}
    </div>
  );
}
